/*
SQLyog Ultimate v11.11 (64 bit)
MySQL - 5.6.16 : Database - db_travlendar
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`db_travlendar` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `db_travlendar`;

/*Table structure for table `estimation` */

DROP TABLE IF EXISTS `estimation`;

CREATE TABLE `estimation` (
  `NOMOR` int(11) NOT NULL AUTO_INCREMENT,
  `DEPARTURELOCATION` varchar(25) DEFAULT NULL,
  `ARRIVSLLOCATION` varchar(25) DEFAULT NULL,
  `DISTANCE` int(11) DEFAULT NULL,
  `ESTIMATION` int(11) DEFAULT NULL,
  PRIMARY KEY (`NOMOR`),
  UNIQUE KEY `ESTIMATION_PK` (`NOMOR`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `estimation` */

/*Table structure for table `event` */

DROP TABLE IF EXISTS `event`;

CREATE TABLE `event` (
  `EVENTID` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `NOMOR` int(11) NOT NULL,
  `LOCATIONID` int(11) NOT NULL,
  `TRANSPORTATIONID` int(11) NOT NULL,
  `EVENTNAME` varchar(20) DEFAULT NULL,
  `STARTEVENTTIME` timestamp NULL DEFAULT NULL,
  `ENDEVENTTIME` timestamp NULL DEFAULT NULL,
  `ARRIVALTIME` timestamp NULL DEFAULT NULL,
  `PRIORITY` int(11) DEFAULT NULL,
  PRIMARY KEY (`EVENTID`),
  UNIQUE KEY `EVENT_PK` (`EVENTID`),
  KEY `RELATIONSHIP_1_FK` (`LOCATIONID`),
  KEY `RELATIONSHIP_2_FK` (`TRANSPORTATIONID`),
  KEY `RELATIONSHIP_3_FK` (`NOMOR`),
  CONSTRAINT `FK_EVENT_RELATIONS_ESTIMATI` FOREIGN KEY (`NOMOR`) REFERENCES `estimation` (`NOMOR`),
  CONSTRAINT `FK_EVENT_RELATIONS_LOCATION` FOREIGN KEY (`LOCATIONID`) REFERENCES `location` (`LOCATIONID`),
  CONSTRAINT `FK_EVENT_RELATIONS_TRANSPOR` FOREIGN KEY (`TRANSPORTATIONID`) REFERENCES `transportation` (`TRANSPORTATIONID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `event` */

/*Table structure for table `location` */

DROP TABLE IF EXISTS `location`;

CREATE TABLE `location` (
  `LOCATIONID` int(11) NOT NULL AUTO_INCREMENT,
  `LOCATIONNAME` varchar(25) DEFAULT NULL,
  `ADDRESS` varchar(40) DEFAULT NULL,
  `TIMEZONE` int(11) DEFAULT NULL,
  PRIMARY KEY (`LOCATIONID`),
  UNIQUE KEY `LOCATION_PK` (`LOCATIONID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `location` */

/*Table structure for table `transportation` */

DROP TABLE IF EXISTS `transportation`;

CREATE TABLE `transportation` (
  `TRANSPORTATIONID` int(11) NOT NULL AUTO_INCREMENT,
  `TRANSPOTATIONMODE` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`TRANSPORTATIONID`),
  UNIQUE KEY `TRANSPORTATION_PK` (`TRANSPORTATIONID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `transportation` */

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
